services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: melody_stream
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chinook
    ports:
      - "5432:5432"
    volumes:
      - ./Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

